@port = {{$dotenv PORT}}
@urlBase = http://localhost:{{port}}

@urlProduccion = https://url-shortner-api-totl.onrender.com



### SHORTNER POST
POST {{urlBase}}/shortner HTTP/1.1
Content-Type: application/json

{
   "url": "https://www.reddit.com/r/animalWell/comments/1jku3t9/i_really_want_to_love_this_game_but_the_controls/"
}



### SHORTNER PRODUCTION POST
POST {{urlProduccion}}/shortner HTTP/1.1
Content-Type: application/json

{
   "url": "https://www.reddit.com/r/animalWell/comments/1jku3t9/i_really_want_to_love_this_game_but_the_controls/"
}